#!/usr/bin/env python3
"""
Apply Spanish translations to all ES JSON files by using EN source files.
For every entry in ES that has Korean text, replace with translated Spanish
(using the EN file as reference, applying name mappings and translating).
"""
import json, re, os, sys

EN_DIR = r"C:\workspace\nevergrad\assets\js\i18n\en"
ES_DIR = r"C:\workspace\nevergrad\assets\js\i18n\es"

KOREAN = re.compile(r'[\uAC00-\uD7A3\u1100-\u11FF\u3130-\u318F]')

def has_kor(s):
    return isinstance(s, str) and bool(KOREAN.search(s))

def load(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)

def save(path, data):
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write('\n')

# Name mapping EN->ES
NAME_MAP = {
    "Me": "Yo", "Han Sea": "Han Sea", "Lee Seolhwa": "Lee Seolhwa",
    "Choi Yuna": "Choi Yuna", "Kang Riin": "Kang Riin", "Park Eunsu": "Park Eunsu",
    "Homeroom Teacher": "Tutora", "Riin": "Riin", "Yuna": "Yuna",
    "Girl A": "Chica A", "Boy B": "Chico B", "Boy next seat": "Chico del asiento de al lado",
    "???": "???", "": "",
}

# All manual translations: {file_stem: {key: {field: value}}}
T = {}

def t(stem, key, **kw):
    T.setdefault(stem, {})[key] = kw

# ─────────────────────────────────────────────
# day2_night
# ─────────────────────────────────────────────
t("day2_night","day2_night_phone_1", text="*Reviso el teléfono de nuevo.*")
t("day2_night","day2_night_phone_2", text="*El grupo de la antigua escuela. El mensaje que mandé ayer... tenía '0 lecturas', pero ahora al revisarlo ha cambiado a '3 lecturas'.*")
t("day2_night","day2_night_phone_3", text="*Lo leyeron. Pero nadie contestó. ...Bueno, deben de estar ocupados.*")
t("day2_night","day2_night_phone_4", text="*Le mando un mensaje privado a Minsu. '¡Ey Minsu, me cambié de colegio, ¿por qué no me has escrito?'*")
t("day2_night","day2_night_phone_5", text="*10 minutos después.*")
t("day2_night","day2_night_phone_6", text="*...¿Por qué tarda tanto? Este tío normalmente responde al segundo.*")
t("day2_night","day2_night_phone_7", text="*5 segundos. El indicador de escritura sigue parpadeando. ¿Estará escribiendo algo largo?*")
t("day2_night","day2_night_phone_8", text="*Llegó la respuesta.*")
t("day2_night","day2_night_phone_9", text="*Minsu: 'Sí, estoy bien. ¿Qué tal por allá?'*")
t("day2_night","day2_night_phone_10", text="*...¿Qué es esto? Le pregunté por qué no me había escrito, y en vez de responder me pregunta '¿qué tal por allá?'*")
t("day2_night","day2_night_phone_11", text="*¿Es en serio Minsu? Normalmente empezaría con 'tío, por fin contestas' y me soltaría un insulto de broma.*")
t("day2_night","day2_night_phone_12", text="*'Sí, estoy bien.' ...¿Eso es lo que tardó 5 segundos en escribir?*")
t("day2_night","day2_night_msg_1", text="*Tengo un mensaje de Seoa.*")
t("day2_night","day2_night_msg_2", text="*Seoa: 'Gracias por hoy también. Por venir a la sala del consejo.'*")
t("day2_night","day2_night_msg_3", text="*Seoa: '¡Comamos juntos mañana también!'*")
t("day2_night","day2_night_msg_4", text="*Seoa: '...Me siento bien cuando estoy con {name}.'*")
t("day2_night","day2_night_msg_5", text="*...El tercer mensaje. 'Me siento bien.' No sé si es solo amabilidad o si tiene otro significado. ...Puede que las dos cosas.*")
t("day2_night","day2_night_msg_6", text="*Le mando una respuesta. 'Yo también lo pasé bien hoy. Nos vemos mañana.'*")
t("day2_night","day2_night_msg_7", text="*Seoa: '♡' ...Un corazón. Qué directa es.*")
t("day2_night","day2_night_sleep_1", text="*Me tumbo en la cama y miro el techo.*")
t("day2_night","day2_night_sleep_2", text="*Lo del contacto con el colegio anterior me da vueltas en la cabeza... pero bueno, se resolverá mañana. Cierro los ojos. Estoy agotado. La conciencia se va difuminando.*")
t("day2_night","day2_night_dream_1", text="*...Camino por un pasillo oscuro.*")
t("day2_night","day2_night_dream_7", text="*Al fondo del pasillo hay alguien de pie. Cara pálida. Ojos que miran lejos. Pelo largo y negro.*")
t("day2_night","day2_night_dream_8", text="*...¿La chica del asiento de atrás? ¿Seolhwa?*")
t("day2_night","day2_night_dream_9", text="*Me acerco. Un paso, dos pasos. Los pasos resuenan. Su boca se mueve.*")
t("day2_night","day2_night_dream_10", name="???", text="\"...Recuérdame...\"")
t("day2_night","day2_night_dream_11", text="*Extendí la mano. Parecía que iba a alcanzarla. En el momento en que mis dedos estaban a punto de tocarla—*")
t("day2_night","day2_night_dream_12", text="*El suelo se desmorona y la vista se oscurece. Caigo. Sin fin.*")
t("day2_night","day2_night_wake_1", text="*...¡! Me desperté empapado en sudor. El corazón me late desbocado.*")
t("day2_night","day2_night_wake_2", text="*Miro el reloj. Las 3:47 de la madrugada.*")
t("day2_night","day2_night_wake_3", text="*Era un sueño. Solo un sueño. ...¿Verdad?*")
t("day2_night","day2_night_wake_4", text="*...Pero ¿por qué recuerdo la cara de Seolhwa con tanta nitidez?*")
t("day2_night","day2_night_wake_5", text="*Bebo un vaso de agua y me vuelvo a tumbar. El sueño no llega.*")

# ─────────────────────────────────────────────
# day3_morning
# ─────────────────────────────────────────────
t("day3_morning","day3_morning_3", text="*Día 3.*")
t("day3_morning","day3_morning_4", text="*Me desperté. El techo blanco. La cama de la residencia.*")
t("day3_morning","day3_morning_5", text="*...Aquella chica del sueño. Seolhwa. Extendí la mano pero no llegué. Al final me caí.*")
t("day3_morning","day3_morning_milk", text="*De camino al colegio, me detuve en la máquina expendedora. Leche de chocolate.*")
t("day3_morning","day3_morning_milk_2", text="*...¿Por qué me apetece ahora esto? Tampoco es que me guste especialmente.*")
t("day3_morning","day3_morning_gate", text="*La entrada del colegio. El olor a flores de cerezo es ligeramente distinto hoy.*")
t("day3_morning","day3_morning_gate_2", text="*No, quizás es mi imaginación. El cansancio del sueño me tiene los sentidos alterados.*")
t("day3_morning","day3_morning_gate_3", text="*Entro por la puerta. Los estudiantes pasan normalmente.*")
t("day3_morning","day3_morning_seolhwa", text="*El aula. El asiento de atrás.*")
t("day3_morning","day3_morning_seolhwa_2", text="*...El asiento de Seolhwa está vacío. ¿Hoy también falta?*")
t("day3_morning","day3_morning_seolhwa_3", text="*Seolhwa. Lee Seolhwa. Nunca la han llamado durante el control de asistencia. La primera vez que la vi fue en el aula, justo después de que empezara la clase.*")
t("day3_morning","day3_morning_seolhwa_4", text="*¿En qué momento se sienta? ¿Cuándo va al baño? Llevo dos días en esta escuela y no he visto que se mueva ni una sola vez.*")
t("day3_morning","day3_morning_seolhwa_5", text="*...¿Quién es esta chica?*")
t("day3_morning","day3_morning_seolhwa_voice", text="*De repente, un susurro desde algún lugar.*")
t("day3_morning","day3_morning_seolhwa_voice_2", text="*Sonido de voz humana. Sin duda. Pero no logro entender lo que dice.*")
t("day3_morning","day3_morning_seolhwa_gone", text="*Me doy la vuelta. No hay nadie.*")
t("day3_morning","day3_morning_seolhwa_gone_2", text="*Solo el silencio del aula vacía. Los demás compañeros aún no han llegado.*")
t("day3_morning","day3_morning_seolhwa_gone_3", text="*...¿Me lo imaginé? ¿O es que estoy demasiado cansado?*")
t("day3_morning","day3_morning_cherry", text="*Por la ventana se ve el patio. Los cerezos están en plena floración.*")
t("day3_morning","day3_morning_cherry_2", text="*...El día 1 también había cerezos. Qué raro que sigan así. ¿No deberían estar cayendo los pétalos?*")
t("day3_morning","day3_morning_class_sea_2", text="*Sea está sentada a mi lado. Como si fuera lo más natural del mundo.*")
t("day3_morning","day3_morning_class_sea_3", text="*No digo nada. Ella tampoco. Solo la clase continúa.*")
t("day3_morning","day3_morning_class_reply", text="*En el descanso. Sea me mira de reojo.*")
t("day3_morning","day3_morning_class_sea_sleep", text="*...Sea se ha quedado dormida en clase. Apoya la cabeza sobre el pupitre y respira lentamente.*")
t("day3_morning","day3_morning_class_sea_sleep_2", text="*Qué raro. Sea nunca se duerme en clase. ¿Se quedó despierta anoche?*")
t("day3_morning","day3_morning_class_eunsu", text="*La profesora Eunsu imparte la clase mirando al frente. Su explicación es suave y apacible.*")
t("day3_morning","day3_morning_class_eunsu_2", text="*...Pero hoy, la voz de la profesora suena un poco diferente. No sé exactamente cómo.*")
t("day3_morning","day3_morning_class_eunsu_3", text="*¿Más lenta? ¿Más baja? O quizás son mis oídos los que están mal.*")
t("day3_morning","day3_morning_class_eunsu_4", text="*La clase continúa. El tiempo pasa lentamente.*")
t("day3_morning","day3_morning_pencil", text="*Dejo caer el bolígrafo. Se cae al suelo.*")
t("day3_morning","day3_morning_pencil_2", text="*Cuando lo recojo... hay algo pegado bajo el pupitre.*")
t("day3_morning","day3_morning_pencil_3", text="*Un papel pequeño. ¿Cuándo lo pusieron aquí? Lo despego discretamente.*")

# ─────────────────────────────────────────────
# day3_lunch
# ─────────────────────────────────────────────
t("day3_lunch","day3_lunch_note", text="*'Hoy en el almuerzo, ve al pasillo del fondo de la tercera planta, edificio antiguo. Hay algo que debo contarte. — Yuna'*")
t("day3_lunch","day3_lunch_note_2", text="*...Una nota de Yuna. ¿Cuándo la puso aquí?*")
t("day3_lunch","day3_lunch_choice", text="*Almuerzo — ¿adónde voy?*",
  choices=["Seguir el mensaje de Yuna — ir al pasillo del fondo",
           "Comer con Sea como de costumbre",
           "Ir a ver a Riin",
           "Comer solo"])
t("day3_lunch","day3_lunch_sea_2", text="*Sea está esperando en el aula. Con una fiambrera preparada.*")
t("day3_lunch","day3_lunch_sea_3", name="Han Sea", text="\"Hoy también hay bastante. Come bien.\"")
t("day3_lunch","day3_lunch_sea_4", text="*Sea abre la fiambrera. Los mismos platos de siempre.*")
t("day3_lunch","day3_lunch_sea_5", text="*Tortilla enrollada, salchichas, bolas de arroz. Perfectamente ordenados.*")
t("day3_lunch","day3_lunch_sea_6", text="*...Los mismos de ayer. Y de antes de ayer.*")
t("day3_lunch","day3_lunch_sea_7", text="\"Sea, ¿siempre preparas lo mismo?\"")
t("day3_lunch","day3_lunch_sea_8", name="Han Sea", text="\"¿A que sí? Son tus favoritos. Sabía que te gustarían.\"")
t("day3_lunch","day3_lunch_riin", text="*La enfermería. Riin está en su mesa, como siempre.*")
t("day3_lunch","day3_lunch_riin_2", name="Kang Riin", text="\"Vaya, hoy también has venido. ¿Estás bien?\"")
t("day3_lunch","day3_lunch_riin_3", text="\"Sí, solo quería pasar.\"")
t("day3_lunch","day3_lunch_riin_4", name="Kang Riin", text="\"Qué bien. Siéntate. Te preparo té.\"")
t("day3_lunch","day3_lunch_riin_choice", text="*Riin saca una taza. Té de hierbas. El mismo olor de siempre.*",
  choices=["Beber el té", "Rechazarlo"])
t("day3_lunch","day3_lunch_riin_drink", text="*Bebo el té. Está caliente. Tiene un sabor dulce.*")
t("day3_lunch","day3_lunch_riin_drink_2", text="*...¿Por qué hoy huele diferente? No a manzanilla. Un olor más dulce, un poco extraño.*")
t("day3_lunch","day3_lunch_riin_refuse", text="\"No, hoy no, gracias.\"")
t("day3_lunch","day3_lunch_riin_refuse_2", name="Kang Riin", text="\"¿Ah sí? De acuerdo. Cuéntame si en algún momento no te encuentras bien.\"")
t("day3_lunch","day3_lunch_alone", text="*La azotea. Sola.*")
t("day3_lunch","day3_lunch_alone_2", text="*El viento sopla. Los pétalos de cerezo flotan.*")
t("day3_lunch","day3_lunch_alone_3", text="*...Hoy también los mismos cerezos. El mismo viento. El mismo cielo.*")
t("day3_lunch","day3_lunch_alone_4", text="*Pero algo es diferente. No sé el qué.*")

# ─────────────────────────────────────────────
# day3_afterschool
# ─────────────────────────────────────────────
t("day3_afterschool","day3_after_riin_flicker", name="", text="Huye")
t("day3_afterschool","day3_after_sea_truth_3", text="*Sea me mira. Sus ojos son diferentes a los de siempre.*")
t("day3_afterschool","day3_after_sea_truth_4", name="Han Sea", text="\"...{name}, ¿en serio quieres saberlo?\"")
t("day3_afterschool","day3_after_sea_truth_5", text="\"Sí. Cuéntame la verdad.\"")
t("day3_afterschool","day3_after_sea_truth_6", name="Han Sea", text="\"...Seolhwa. Lee Seolhwa. Era compañera de esta clase hasta el semestre pasado.\"")
t("day3_afterschool","day3_after_sea_truth_7", name="Han Sea", text="\"Pero un día... desapareció. De repente. Y nadie habla de ello.\"")
t("day3_afterschool","day3_after_eunsu_peek_4", name="Park Eunsu", text="\"...¿{name}? ¿Qué haces aquí?\"")
t("day3_afterschool","day3_after_eunsu_peek_5", text="\"Nada, solo pasaba.\"")
t("day3_afterschool","day3_after_eunsu_peek_6", name="Park Eunsu", text="\"Ya veo. Vuelve al aula. No deberías estar en este pasillo.\"")
t("day3_afterschool","day3_after_eunsu_ignore_3", text="*Miro dentro de la habitación. Está oscuro. No se ve nada.*")
t("day3_afterschool","day3_after_eunsu_ignore_4", text="*Pero hay algo. Un olor. A desinfectante mezclado con algo más.*")

# ─────────────────────────────────────────────
# day3_night
# ─────────────────────────────────────────────
t("day3_night","day3_night_start_2", text="*De vuelta en la residencia.*")
t("day3_night","day3_night_start_3", text="*Me siento en la cama. Las manos me tiemblan un poco.*")
t("day3_night","day3_night_start_4", text="*Lo que vi hoy. El sótano. Esa habitación. El olor a desinfectante.*")
t("day3_night","day3_night_start_5", text="*La foto de Yuna. El pasillo oscuro. La puerta cerrada.*")
t("day3_night","day3_night_start_6", text="*Y Sea. 'Desapareció.' ¿Qué significa eso?*")
t("day3_night","day3_night_start_7", text="*¿Dónde está Seolhwa ahora? ¿Por qué su asiento sigue ahí, vacío?*")
t("day3_night","day3_night_start_8", text="*Demasiadas preguntas. Y ninguna respuesta.*")
t("day3_night","day3_night_start_9", text="*Miro el teléfono. Ningún mensaje nuevo.*")
t("day3_night","day3_night_sea_msg", text="*Llega un mensaje de Sea.*")
t("day3_night","day3_night_sea_msg_2", name="Han Sea", text="\"Oye, ¿estás bien? Hoy parecías rara.\"")
t("day3_night","day3_night_sea_msg_3", text="\"Estoy bien. Solo un poco cansada.\"")
t("day3_night","day3_night_sea_msg_4", name="Han Sea", text="\"¿De verdad? ...Cuídate. Mañana nos vemos.\"")
t("day3_night","day3_night_sea_msg_5", text="*Un mensaje corto. Pero el tono es distinto al de siempre.*")
t("day3_night","day3_night_sea_msg_6", text="*¿Sabe que estuve en ese pasillo?*")
t("day3_night","day3_night_sea_msg_7", name="Han Sea", text="\"...{name}. En este colegio, hay cosas que no debes buscar.\"")
t("day3_night","day3_night_sea_msg_8", text="*El mensaje llegó después de un largo silencio.*")
t("day3_night","day3_night_sea_msg_9", name="Han Sea", text="\"Por favor. Por tu bien.\"")
t("day3_night","day3_night_recall_5", text="*La cara de Seolhwa. La vi en sueños. Cara pálida, ojos que miran lejos.*")
t("day3_night","day3_night_recall_6", text="*'Recuérdame.' Eso fue lo que dijo.*")
t("day3_night","day3_night_recall_7", text="*¿Qué pasó con Seolhwa? ¿Por qué nadie habla de ella?*")
t("day3_night","day3_night_recall_8", text="*Y esa habitación del sótano. Esa silla. Esas correas de cuero.*")
t("day3_night","day3_night_recall_9", text="*...No quiero saberlo. Pero si no lo busco, nadie lo hará.*")
t("day3_night","day3_night_stat_crack_3", text="*...Siento que algo se está agrietando. Algo que no debería romperse.*")
t("day3_night","day3_night_stat_crack_4", text="*Dentro de mí. Dentro de este colegio.*")
t("day3_night","day3_night_stat_crack_5", text="*Aún no puedo verlo con claridad. Pero está ahí.*")
t("day3_night","day3_night_nightmare_9", text="*Seolhwa está sentada en esa silla. Las correas sujetan sus muñecas.*")
t("day3_night","day3_night_nightmare_10", name="Lee Seolhwa", text="\"...¿Por qué no viniste antes?\"")
t("day3_night","day3_night_nightmare_11", text="*No puedo responder. Las piernas no me responden.*")
t("day3_night","day3_night_nightmare_12", name="Lee Seolhwa", text="\"Ya es demasiado tarde para mí. Pero tú... todavía puedes salir.\"")
t("day3_night","day3_night_seolhwa_5", text="*Camino por el pasillo oscuro. Esto es... la escuela. El pasillo de la escuela de noche.*")
t("day3_night","day3_night_seolhwa_6", text="*Al fondo. Seolhwa está de pie.*")
t("day3_night","day3_night_seolhwa_7", name="Lee Seolhwa", text="\"...Viniste.\"")
t("day3_night","day3_night_seolhwa_8", text="\"Seolhwa. ¿Qué te pasó? ¿Dónde estás ahora?\"")
t("day3_night","day3_night_seolhwa_9", name="Lee Seolhwa", text="\"Ya no importa dónde estoy. Lo que importa eres tú.\"")
t("day3_night","day3_night_seolhwa_10", name="Lee Seolhwa", text="\"Sal de aquí. Antes del quinto día.\"")
t("day3_night","day3_night_seolhwa_11", text="\"¿Antes del quinto día? ¿Por qué?\"")
t("day3_night","day3_night_seolhwa_12", name="Lee Seolhwa", text="\"Porque en el quinto día... ya no podrás salir.\"")
t("day3_night","day3_night_seolhwa_13", text="\"¿Qué significa eso? ¿Qué pasa en el quinto día?\"")
t("day3_night","day3_night_seolhwa_14", name="Lee Seolhwa", text="\"El tratamiento se completa. Después de eso... ya no recordarás nada.\"")
t("day3_night","day3_night_seolhwa_15", text="\"¿Tratamiento? ¿Qué tratamiento?\"")
t("day3_night","day3_night_seolhwa_16", name="Lee Seolhwa", text="\"El té. Las medicinas. Las inyecciones. Todo va borrando poco a poco tus recuerdos.\"")
t("day3_night","day3_night_seolhwa_17", text="\"...¿Eso es lo que les está pasando a todos en este colegio?\"")
t("day3_night","day3_night_seolhwa_18", name="Lee Seolhwa", text="\"Sí. Todos ya han sido... completados. Solo tú no.\"")
t("day3_night","day3_night_seolhwa_19", text="\"¿Completados? ¿Qué quieres decir con completados?\"")
t("day3_night","day3_night_seolhwa_20", name="Lee Seolhwa", text="\"Estudiantes perfectos. Que obedecen. Que no se rebelan. Que no recuerdan el mundo exterior.\"")
t("day3_night","day3_night_seolhwa_21", text="*El frío me recorre la espalda.*")
t("day3_night","day3_night_seolhwa_22", name="Lee Seolhwa", text="\"Yo también intenté salir. Pero fracasé. Por eso... soy como soy ahora.\"")
t("day3_night","day3_night_seolhwa_23", text="*La forma de Seolhwa empieza a volverse translúcida. Como si se disolviera.*")
t("day3_night","day3_night_wakeup_4", text="*Me desperté. Estaba sudando.*")
t("day3_night","day3_night_wakeup_5", text="*Las 2:13 de la madrugada.*")
t("day3_night","day3_night_wakeup_6", text="*...Era un sueño. Pero lo que me dijo Seolhwa... lo recuerdo todo con claridad.*")
t("day3_night","day3_night_wakeup_7", text="*'Sal antes del quinto día.'*")
t("day3_night","day3_night_wakeup_8", text="*'Después de eso, ya no podrás salir.'*")
t("day3_night","day3_night_wakeup_9", text="*...Queda el día 4 y el día 5. Tengo que encontrar una manera de salir.*")
t("day3_night","day3_night_investigate_3", text="*Busco en internet. Pero no encuentro nada sobre este colegio. Ni un artículo. Ni una reseña.*")
t("day3_night","day3_night_deny_3", text="*...Solo son sueños. No significa nada. Es el estrés de la transferencia. Eso es todo.*")
t("day3_night","day3_night_ghost_msg", name="", text="*¿De verdad estará bien?*")

# ─────────────────────────────────────────────
# day4_morning
# ─────────────────────────────────────────────
t("day4_morning","day4_morning_start_4", text="*Día 4.*")
t("day4_morning","day4_morning_start_5", text="*El despertador sonó. Me senté en la cama.*")
t("day4_morning","day4_morning_start_6", text="*Queda hoy y mañana. Antes del quinto día.*")
t("day4_morning","day4_morning_start_7", text="*Tengo que salir. No sé cómo todavía. Pero tengo que salir.*")
t("day4_morning","day4_morning_start_8", text="*Me pongo el uniforme. Me miro en el espejo. Mi cara... parece diferente a la del día 1.*")
t("day4_morning","day4_morning_start_9", text="*Los ojos. Algo en los ojos es diferente. Como si supieran algo que no deberían saber.*")
t("day4_morning","day4_morning_commute", text="*De camino al colegio. El mismo trayecto de siempre.*")
t("day4_morning","day4_morning_commute_2", text="*Pero hoy, el entorno parece diferente. Los árboles, las casas, las personas.*")
t("day4_morning","day4_morning_commute_3", text="*...¿Cuándo fue la última vez que vi a alguien fuera del colegio? ¿Fue ayer? ¿Anteayer?*")
t("day4_morning","day4_morning_gate_4", text="*La entrada del colegio. Antes de cruzar, me detengo.*")
t("day4_morning","day4_morning_gate_5", text="*La puerta está abierta. Los estudiantes pasan.*")
t("day4_morning","day4_morning_gate_6", text="*...¿Podría darme la vuelta ahora mismo? ¿Simplemente salir corriendo?*")
t("day4_morning","day4_morning_eunsu_3", text="*¿Qué hago?*",
  choices=["Ir con la profesora", "Escapar ahora"])
t("day4_morning","day4_morning_eunsu_comply_2", text="*La profesora Eunsu me lleva de vuelta al aula. Su mano en mi hombro es firme.*")
t("day4_morning","day4_morning_eunsu_comply_3", name="Park Eunsu", text="\"{name}, no tienes que ir a ningún sitio. Aquí estás a salvo.\"")
t("day4_morning","day4_morning_eunsu_refuse_3", text="*Intenté correr. Pero las piernas no me respondían.*")
t("day4_morning","day4_morning_eunsu_refuse_4", text="*La profesora Eunsu me coge del brazo. Su agarre es suave pero no puedo soltarme.*")
t("day4_morning","day4_morning_classroom_4", text="*El aula. Los mismos compañeros de siempre. Las mismas caras.*")
t("day4_morning","day4_morning_classroom_5", text="*Pero hoy... todos parecen estar mirándome. Sin que yo se lo pida.*")
t("day4_morning","day4_morning_sea_4", text="*Sea se sienta a mi lado. Más cerca que de costumbre.*")
t("day4_morning","day4_morning_sea_5", name="Han Sea", text="\"...{name}. Hoy quédate cerca de mí.\"")
t("day4_morning","day4_morning_sea_6", text="*Las palabras de Sea. No como una propuesta. Como una advertencia.*")
t("day4_morning","day4_morning_class_5", text="*La clase de la profesora Eunsu continúa.*")
t("day4_morning","day4_morning_class_6", text="*Pero no puedo concentrarme. Las palabras de Seolhwa del sueño me dan vueltas en la cabeza.*")
t("day4_morning","day4_morning_class_7", text="*'Sal antes del quinto día.'*")
t("day4_morning","day4_morning_class_8", text="*Hoy es el cuarto día. Mañana es el quinto.*")
t("day4_morning","day4_morning_class_9", text="*...Tengo que actuar. Hoy.*")

# ─────────────────────────────────────────────
# day4_lunch
# ─────────────────────────────────────────────
t("day4_lunch","day4_lunch_start_3", text="*La hora del almuerzo. Tengo que moverme.*")
t("day4_lunch","day4_lunch_start_4", text="*Yuna. La nota. 'Hay algo que debo contarte.'*")
t("day4_lunch","day4_lunch_start_5", text="*Fui al pasillo del fondo de la tercera planta. Yuna estaba esperando.*")
t("day4_lunch","day4_lunch_search_7", text="*Yuna me tiende algo. Una tarjeta de memoria.*")
t("day4_lunch","day4_lunch_search_8", name="Choi Yuna", text="\"Senpai. Esto... es de Seolhwa-senpai.\"")
t("day4_lunch","day4_lunch_search_9", text="\"¿De Seolhwa? ¿Cómo la conseguiste?\"")
t("day4_lunch","day4_lunch_search_10", name="Choi Yuna", text="\"La encontré. En el sótano. Cuando fui a buscar evidencias.\"")
t("day4_lunch","day4_lunch_search_11", text="\"¿El sótano? ¿Fuiste ahí sola?\"")
t("day4_lunch","day4_lunch_search_12", name="Choi Yuna", text="\"Sí. Tenía miedo pero... quería saber la verdad.\"")
t("day4_lunch","day4_lunch_search_13", text="*Yuna abraza la cámara con fuerza. Tiene las manos temblando.*")
t("day4_lunch","day4_lunch_search_14", name="Choi Yuna", text="\"Senpai. En esta tarjeta de memoria... creo que hay registros de lo que le hicieron a Seolhwa-senpai.\"")
t("day4_lunch","day4_lunch_search_15", text="*Me quedo sin habla.*")
t("day4_lunch","day4_lunch_search_16", name="Choi Yuna", text="\"No tuve el valor de mirarlo. Senpai... ¿puedes hacerlo tú?\"")
t("day4_lunch","day4_lunch_search_17", text="*Tomo la tarjeta de memoria. Está fría.*")
t("day4_lunch","day4_lunch_nurse_5", text="*La enfermería. Riin está de espaldas, preparando algo.*")
t("day4_lunch","day4_lunch_nurse_6", text="*...No lo sabe. Que estoy aquí.*")
t("day4_lunch","day4_lunch_nurse_7", text="*Hay papeles sobre la mesa. Registros. Nombres.*")
t("day4_lunch","day4_lunch_nurse_8", text="*Un nombre familiar. Lee Seolhwa.*")
t("day4_lunch","day4_lunch_nurse_9", text="*Junto a él... fechas. Dosis. 'Tratamiento completado'.*")
t("day4_lunch","day4_lunch_nurse_10", text="*Las manos me tiemblan. Esto es...*")
t("day4_lunch","day4_lunch_nurse_11", text="*Riin se da la vuelta.*")
t("day4_lunch","day4_lunch_nurse_timer", text="*¿Qué hago?*",
  choices=["Esconderme", "Hacer como si nada"])
t("day4_lunch","day4_lunch_nurse_ask", text="*Me acerco. Finjo naturalidad.*")
t("day4_lunch","day4_lunch_nurse_ask_2", name="Kang Riin", text="\"Vaya, ¿hoy también viniste? Siéntate.\"")
t("day4_lunch","day4_lunch_nurse_ask_3", text="\"Sí. Quería pasar.\"")
t("day4_lunch","day4_lunch_nurse_ask_4", name="Kang Riin", text="\"¿Estás bien? Hoy pareces tensa.\"")
t("day4_lunch","day4_lunch_nurse_ask_5", text="\"Estoy bien. Solo un poco cansada.\"")
t("day4_lunch","day4_lunch_nurse_ask_6", name="Kang Riin", text="\"Ya veo. Toma, te preparo el té.\"")
t("day4_lunch","day4_lunch_nurse_ask_7", text="*Riin pone el agua a hervir. Yo sigo pensando en aquellos documentos.*")
t("day4_lunch","day4_lunch_nurse_ask_8", text="*Lee Seolhwa. Tratamiento completado. Esas palabras.*")
t("day4_lunch","day4_lunch_nurse_ask_9", name="Kang Riin", text="\"...¿{name}? ¿En qué estás pensando?\"")
t("day4_lunch","day4_lunch_nurse_ask_10", text="\"Nada. Perdona.\"")
t("day4_lunch","day4_lunch_nurse_silent", text="*Me escondo detrás de la estantería. Riin pasa cerca.*")
t("day4_lunch","day4_lunch_nurse_silent_2", text="*...No me ve. Sale de la enfermería.*")
t("day4_lunch","day4_lunch_nurse_silent_3", text="*Cuando se va, vuelvo a mirar los documentos.*")
t("day4_lunch","day4_lunch_nurse_silent_4", text="*Lee Seolhwa. Día 1 al Día 5. 'Tratamiento completado'.*")
t("day4_lunch","day4_lunch_nurse_silent_5", text="*Debajo... otros nombres. Nombres que no reconozco.*")
t("day4_lunch","day4_lunch_nurse_silent_6", text="*Cuántas personas. Cuántos...*")
t("day4_lunch","day4_lunch_rooftop_6", text="*La azotea. Saco el teléfono. Miro los archivos de la tarjeta de memoria.*")
t("day4_lunch","day4_lunch_rooftop_7", text="*Fotos. Documentos. Archivos de video.*")
t("day4_lunch","day4_lunch_rooftop_8", text="*Abro uno. Un pasillo oscuro. Una habitación. Esa silla.*")
t("day4_lunch","day4_lunch_rooftop_9", text="*Y en ella... Seolhwa.*")
t("day4_lunch","day4_lunch_rooftop_10", text="*Con las muñecas sujetas. La cabeza gacha. No se mueve.*")
t("day4_lunch","day4_lunch_rooftop_11", text="*Alguien le pone una inyección. La cámara tiembla.*")
t("day4_lunch","day4_lunch_rooftop_12", name="Lee Seolhwa", text="\"...Recuérdame. Por favor.\"")
t("day4_lunch","day4_lunch_rooftop_13", text="*El vídeo se corta.*")

# ─────────────────────────────────────────────
# day4_afterschool
# ─────────────────────────────────────────────
t("day4_afterschool","day4_after_start_3", text="*Después de clases.*")
t("day4_afterschool","day4_after_start_4", text="*El vídeo de Seolhwa. Esas imágenes no puedo quitármelas de la cabeza.*")
t("day4_afterschool","day4_after_basement_10", text="*La puerta del sótano está abierta.*")
t("day4_afterschool","day4_after_basement_11", text="*Entro. Está oscuro. El olor a desinfectante es más fuerte.*")
t("day4_afterschool","day4_after_basement_12", text="*Una habitación al fondo del pasillo. La misma del vídeo.*")
t("day4_afterschool","day4_after_basement_13", text="*La silla. Las correas de cuero.*")
t("day4_afterschool","day4_after_basement_14", text="*Y en la pared... fotos. Muchas fotos.*")
t("day4_afterschool","day4_after_basement_15", text="*Caras de estudiantes. Nombres. Fechas.*")
t("day4_afterschool","day4_after_basement_16", text="*Los miro uno por uno. Nombres que no reconozco. Y luego...*")
t("day4_afterschool","day4_after_basement_17", text="*Lee Seolhwa. Con una gran X roja.*")
t("day4_afterschool","day4_after_basement_18", text="*...¿Qué significa esta X?*")
t("day4_afterschool","day4_after_basement_19", text="*Sigo mirando. Más fotos. Más X.*")
t("day4_afterschool","day4_after_basement_20", text="*Todos completados. Todos con X.*")
t("day4_afterschool","day4_after_basement_21", text="*...Y al final, mi foto. Sin X todavía.*")
t("day4_afterschool","day4_after_basement_22", text="*Mi nombre. Mi cara. Fecha: Día 5.*")
t("day4_afterschool","day4_after_basement_23", text="*Mañana. Me hacen esto mañana.*")
t("day4_afterschool","day4_after_basement_24", text="*Se me doblan las rodillas. Me agarro a la pared.*")
t("day4_afterschool","day4_after_basement_25", text="*...Tengo que salir. Hoy mismo.*")
t("day4_afterschool","day4_after_basement_26", text="*Escucho pasos. Alguien baja las escaleras.*")
t("day4_afterschool","day4_after_basement_timer", text="*¿Qué hago?*",
  choices=["Esconderme", "Salir corriendo"])
t("day4_afterschool","day4_after_basement_rescue_3", text="*Me escondo. Los pasos pasan de largo.*")
t("day4_afterschool","day4_after_basement_rescue_4", text="*...Era Riin. Llevaba algo en las manos.*")
t("day4_afterschool","day4_after_basement_rescue_5", text="*Cuando el sonido de sus pasos se aleja, salgo corriendo.*")
t("day4_afterschool","day4_after_basement_hide_3", text="*Salgo corriendo. Pero alguien me agarra del brazo.*")
t("day4_afterschool","day4_after_basement_hide_4", name="Kang Riin", text="\"...¿Qué estás haciendo aquí?\"")
t("day4_afterschool","day4_after_basement_hide_5", text="*La voz de Riin. Fría. Diferente a la de siempre.*")
t("day4_afterschool","day4_after_sea_6", text="*Sea me espera en el aula.*")
t("day4_afterschool","day4_after_sea_7", name="Han Sea", text="\"...¿Dónde estabas?\"")
t("day4_afterschool","day4_after_sea_8", text="\"Solo... dando una vuelta.\"")
t("day4_afterschool","day4_after_sea_force", text="*Sea me mira fijamente.*",
  choices=["Contarle la verdad", "Seguir mintiendo"])
t("day4_afterschool","day4_after_sea_accept_3", text="*Sea escucha en silencio. Cuando termino, baja la vista.*")
t("day4_afterschool","day4_after_sea_accept_4", name="Han Sea", text="\"...Ya lo sé. Todo.\"")
t("day4_afterschool","day4_after_sea_crack_3", text="*Sea tiembla.*")
t("day4_afterschool","day4_after_sea_crack_4", name="Han Sea", text="\"...Yo también quería salir. Al principio.\"")
t("day4_afterschool","day4_after_sea_crack_5", text="\"¿Al principio?\"")
t("day4_afterschool","day4_after_sea_crack_6", name="Han Sea", text="\"Ahora ya no. Ya no puedo. Me han hecho demasiado.\"")
t("day4_afterschool","day4_after_sea_crack_7", text="*Las manos de Sea tiemblan.*")
t("day4_afterschool","day4_after_sea_crack_8", name="Han Sea", text="\"Pero tú... todavía puedes. No te han completado.\"")
t("day4_afterschool","day4_after_sea_crack_9", text="\"¿Qué significa 'completado'?\"")
t("day4_afterschool","day4_after_sea_crack_10", name="Han Sea", text="\"Que ya no recuerdas nada de antes. Que no quieres salir. Que solo quieres quedarte aquí... para siempre.\"")
t("day4_afterschool","day4_after_sea_crack_11", text="*El frío me recorre la espalda.*")
t("day4_afterschool","day4_after_sea_crack_12", name="Han Sea", text="\"...{name}. Sal mañana. Antes de que sea demasiado tarde.\"")
t("day4_afterschool","day4_after_sea_crack_13", text="\"Sea. Ven conmigo.\"")
t("day4_afterschool","day4_after_sea_crack_14", name="Han Sea", text="\"No puedo. Ya no me queda fuerza para salir.\"")
t("day4_afterschool","day4_after_sea_crack_15", text="\"¡Sí que puedes! Juntas podemos—\"")
t("day4_afterschool","day4_after_sea_crack_16", name="Han Sea", text="\"No. ...No puedo.\"")
t("day4_afterschool","day4_after_sea_crack_17", text="*Las lágrimas ruedan por las mejillas de Sea.*")
t("day4_afterschool","day4_after_sea_crack_18", name="Han Sea", text="\"Pero tú sí. Por eso... sé que puedes hacerlo.\"")
t("day4_afterschool","day4_after_sea_crack_19", text="*Se muerde el labio. Los ojos le brillan con las lágrimas.*")
t("day4_afterschool","day4_after_sea_crack_20", name="Han Sea", text="\"...Ve. {name}.\"")
t("day4_afterschool","day4_after_evidence_7", text="*Saco el teléfono. Fotografío los documentos. Fotografío las fotos de la pared.*")
t("day4_afterschool","day4_after_evidence_8", text="*Tengo las evidencias. Ahora tengo que salir.*")
t("day4_afterschool","day4_after_evidence_9", text="*Pasos en el pasillo. Alguien se acerca.*")
t("day4_afterschool","day4_after_evidence_timer", text="*¿Qué hago?*",
  choices=["Salir corriendo", "Quedarme"])
t("day4_afterschool","day4_after_evidence_run_3", text="*Salgo corriendo por el pasillo. Los pasos se aceleran detrás de mí.*")
t("day4_afterschool","day4_after_evidence_run_4", text="*La puerta de emergencia. Empujo. Está abierta.*")
t("day4_afterschool","day4_after_evidence_run_5", text="*La escalera de emergencia. Bajo de dos en dos.*")
t("day4_afterschool","day4_after_evidence_run_6", text="*El exterior del edificio. La lluvia empieza a caer.*")
t("day4_afterschool","day4_after_evidence_run_7", text="*Corro. Sin mirar atrás.*")
t("day4_afterschool","day4_after_evidence_stay", text="*Me quedo quieta. La puerta se abre.*")
t("day4_afterschool","day4_after_evidence_stay_2", name="Park Eunsu", text="\"...{name}. ¿Qué haces aquí?\"")
t("day4_afterschool","day4_after_evidence_stay_3", text="\"Nada. Me perdí.\"")
t("day4_afterschool","day4_after_evidence_stay_4", name="Park Eunsu", text="\"Ya veo. Vamos. Te acompaño.\"")
t("day4_afterschool","day4_after_evidence_stay_5", text="*La mano de la profesora en mi hombro. Suave pero firme.*")
t("day4_afterschool","day4_after_evidence_stay_6", text="*...¿Vio lo que hice? ¿Lo sabe?*")
t("day4_afterschool","day4_after_evidence_stay_7", name="Park Eunsu", text="\"...{name}. Deberías descansar bien esta noche.\"")
t("day4_afterschool","day4_after_evidence_stay_8", text="\"Sí.\"")
t("day4_afterschool","day4_after_evidence_stay_9", name="Park Eunsu", text="\"Mañana es un día especial. Quiero que estés bien descansada.\"")
t("day4_afterschool","day4_after_evidence_stay_10", text="*'Un día especial.' El quinto día.*")

# ─────────────────────────────────────────────
# day4_night
# ─────────────────────────────────────────────
t("day4_night","day4_night_phone_4", text="*Miro los archivos de la tarjeta de memoria otra vez.*")
t("day4_night","day4_night_phone_5", text="*El vídeo de Seolhwa. La foto de los documentos. Las fotos de los estudiantes en la pared.*")
t("day4_night","day4_night_phone_6", text="*Evidencias. Tengo evidencias.*")
t("day4_night","day4_night_phone_7", text="*Pero ¿de qué sirven si no puedo salir?*")
t("day4_night","day4_night_phone_8", text="*Intento llamar al exterior. Mis amigos de antes. El número de emergencias.*")
t("day4_night","day4_night_phone_9", text="*Pero no hay señal. Ni una sola barra.*")
t("day4_night","day4_night_phone_10", text="*...¿Desde cuándo no hay señal? ¿Siempre fue así?*")
t("day4_night","day4_night_phone_11", text="*Lo intenté en el techo. En el pasillo. En el patio.*")
t("day4_night","day4_night_phone_12", text="*Nada. Cero barras. El colegio bloquea la señal.*")
t("day4_night","day4_night_plan_4", text="*Tengo que planear la huida.*")
t("day4_night","day4_night_plan_5", text="*Mañana es el quinto día. La última oportunidad.*")
t("day4_night","day4_night_plan_6", text="*Durante el almuerzo. Ese es el único momento en que el vigilancia se relaja.*")
t("day4_night","day4_night_plan_7", text="*La puerta de emergencia de la tercera planta, edificio antiguo. Yuna la encontró.*")
t("day4_night","day4_night_plan_8", text="*Llevo las evidencias. Salgo del colegio. Y luego...*")
t("day4_night","day4_night_plan_9", text="*¿Y luego qué? ¿Ir a la policía? ¿Publicarlo en internet?*")
t("day4_night","day4_night_plan_10", text="*Alguien tiene que saber la verdad.*")
t("day4_night","day4_night_plan_11", text="*...¿Y Yuna? ¿Y Sea?*")
t("day4_night","day4_night_plan_12", text="*Sea dijo que no puede salir. Yuna... no sé.*")
t("day4_night","day4_night_plan_13", text="*Pero si me quedo, mañana me hacen lo mismo que a Seolhwa.*")
t("day4_night","day4_night_plan_choice", text="*¿Qué hago con Yuna?*",
  choices=["Llevarla conmigo", "Salir sola"])
t("day4_night","day4_night_plan_escape_2", text="*Le mando un mensaje a Yuna. 'Mañana en el almuerzo, tercera planta, edificio antiguo. Vente conmigo.'*")
t("day4_night","day4_night_plan_escape_3", text="*La respuesta llega rápido. 'De acuerdo, senpai. Iré.'*")
t("day4_night","day4_night_plan_expose_2", text="*Yuna ya ha hecho suficiente. No quiero meterla en más peligro.*")
t("day4_night","day4_night_plan_confront_2", text="*Mañana, en el momento en que intenten completarme... les enseño las evidencias.*")
t("day4_night","day4_night_sleep", text="*Me tumbo en la cama.*")
t("day4_night","day4_night_sleep_2", text="*No puedo dormir. Claro que no.*")
t("day4_night","day4_night_sleep_3", text="*...Si al menos pudiera hablar con alguien. Pero no hay nadie.*")
t("day4_night","day4_night_seolhwa_12", text="*Sueño. Otra vez el mismo pasillo oscuro.*")
t("day4_night","day4_night_seolhwa_13", name="Lee Seolhwa", text="\"...Viniste de nuevo.\"")
t("day4_night","day4_night_seolhwa_14", text="\"Seolhwa. Encontré las evidencias. El vídeo, los documentos.\"")
t("day4_night","day4_night_seolhwa_15", name="Lee Seolhwa", text="\"Lo sé. Lo vi.\"")
t("day4_night","day4_night_seolhwa_16", text="\"Mañana salgo. Voy a llevar estas evidencias al mundo.\"")
t("day4_night","day4_night_seolhwa_17", name="Lee Seolhwa", text="\"...Bien. Pero ten cuidado.\"")
t("day4_night","day4_night_seolhwa_18", text="\"¿Tú vendrás? ¿Puedes salir?\"")
t("day4_night","day4_night_seolhwa_19", name="Lee Seolhwa", text="\"Yo... ya no soy de este mundo. No puedo ir contigo.\"")
t("day4_night","day4_night_seolhwa_20", text="\"¿Qué? Entonces... ¿estás...?\"")
t("day4_night","day4_night_seolhwa_21", name="Lee Seolhwa", text="\"Sí. Desde hace mucho tiempo.\"")
t("day4_night","day4_night_seolhwa_22", text="*No puedo hablar. La forma de Seolhwa empieza a desvanecerse.*")
t("day4_night","day4_night_seolhwa_23", name="Lee Seolhwa", text="\"...Pero si tú sales... al menos alguien lo sabrá. Que yo existí. Que estuve aquí.\"")
t("day4_night","day4_night_seolhwa_24", text="\"Te lo prometo. Lo contaré. Todo.\"")
t("day4_night","day4_night_seolhwa_25", name="Lee Seolhwa", text="\"Gracias. ...{name}.\"")
t("day4_night","day4_night_seolhwa_26", text="*Seolhwa sonríe. Por primera vez, sonríe.*")
t("day4_night","day4_night_seolhwa_28", text="*La forma de Seolhwa se desvanece por completo.*")
t("day4_night","day4_night_seolhwa_29", text="*El pasillo oscuro vuelve a quedar vacío.*")
t("day4_night","day4_night_seolhwa_30", text="*Solo el eco de sus pasos.*")
t("day4_night","day4_night_seolhwa_31", name="Lee Seolhwa", text="\"...No lo olvides.\"")
t("day4_night","day4_night_seolhwa_32", text="*Una última voz.*")
t("day4_night","day4_night_seolhwa_33", name="Lee Seolhwa", text="\"Que yo... existí.\"")
t("day4_night","day4_night_seolhwa_34", text="*Y luego el silencio.*")
t("day4_night","day4_night_seolhwa_35", text="*Me desperté. Las 4 de la madrugada.*")
t("day4_night","day4_night_seolhwa_36", text="*...Las lágrimas me corren por las mejillas.*")
t("day4_night","day4_night_seolhwa_37", text="*Lee Seolhwa. Existió. Estuvo en este colegio. En este aula. En ese asiento.*")
t("day4_night","day4_night_seolhwa_38", text="*Y nadie lo sabe. Nadie lo recuerda.*")
t("day4_night","day4_night_seolhwa_39", text="*Salvo yo.*")
t("day4_night","day4_night_seolhwa_40", text="*Miro el techo. El amanecer empieza a teñir la ventana.*")
t("day4_night","day4_night_seolhwa_41", name="Lee Seolhwa", text="\"...No lo olvides.\"")
t("day4_night","day4_night_seolhwa_42", text="*La voz de Seolhwa todavía resuena en mis oídos.*")
t("day4_night","day4_night_wake", text="*El día 5 ha comenzado.*")
t("day4_night","day4_night_wake_2", text="*El último día.*")
t("day4_night","day4_night_wake_3", text="*Me incorporo. Las manos me tiemblan.*")
t("day4_night","day4_night_wake_4", text="*Pero mi determinación es firme.*")
t("day4_night","day4_night_wake_5", text="*Hoy salgo. Pase lo que pase.*")
t("day4_night","day4_night_wake_6", text="*Por Seolhwa. Por mí. Por todos los que están en este colegio.*")

# ─────────────────────────────────────────────
# day5_morning
# ─────────────────────────────────────────────
t("day5_morning","day5_morning_start_4", text="*Miro por la ventana. El cielo está gris. Las nubes cuelgan bajo. Parece que va a llover.*")
t("day5_morning","day5_morning_start_5", text="*...La mañana del día 1 estaba despejada. Los cerezos estaban en flor. En solo cuatro días, el mundo ha cambiado tanto.*")
t("day5_morning","day5_morning_start_6", text="*No. El mundo no ha cambiado. Es la forma en que lo veo la que ha cambiado.*")
t("day5_morning","day5_morning_start_7", text="*Compruebo la mochila. Las cosas que preparé anoche. El teléfono con las evidencias. La tarjeta de memoria de Yuna. El fragmento de foto.*")
t("day5_morning","day5_morning_start_8", text="*...Tengo que salir hoy. Antes de las 11 de la noche.*")
t("day5_morning","day5_morning_start_9", text="*Me pongo el uniforme. Mi cara en el espejo... no es la del día 1. Los ojos son diferentes. Ojos que han aprendido cómo se ve el miedo.*")
t("day5_morning","day5_morning_start_10", text="*Respiración profunda. Una. Dos. Tres.*")
t("day5_morning","day5_morning_start_11", text="*...Voy.*")
t("day5_morning","day5_morning_gate_4", text="*La entrada principal está abierta. Como siempre. Los estudiantes pasan en pequeños grupos.*")
t("day5_morning","day5_morning_gate_5", text="*...Solo tengo que salir. Pasar la puerta, girar a la izquierda, y allí está la parada de autobús. Tomar cualquier autobús.*")
t("day5_morning","day5_morning_gate_6", text="*Di un paso hacia adelante. Dos pasos. La puerta se acerca.*")
t("day5_morning","day5_morning_gate_choice", text="",
  choices=["Seguir caminando hacia adelante", "Dar media vuelta"])
t("day5_morning","day5_morning_gate_dodge_fail", text="*...Hacia adelante. Tengo que ir hacia adelante.*")
t("day5_morning","day5_morning_paralysis_1", text="*...Al tercer paso, las piernas se detuvieron.*")
t("day5_morning","day5_morning_paralysis_2", text="*No se mueven. Tengo la voluntad de caminar, pero las piernas no obedecen. Como si estuvieran ancladas en cemento.*")
t("day5_morning","day5_morning_paralysis_3", text="*El té que bebí anoche. El té 'para dormir bien' que me dio Riin. ...¿Será posible?*")
t("day5_morning","day5_morning_paralysis_4", text="*Miro alrededor. Los estudiantes pasan por la puerta. Con naturalidad. Sonriendo.*")
t("day5_morning","day5_morning_paralysis_5", text="*Solo yo no puedo moverme. La puerta está abierta. Nadie me bloquea.*")
t("day5_morning","day5_morning_paralysis_6", text="*De pie frente a una puerta abierta sin poder dar un solo paso. Esto... esta es la verdadera cárcel del colegio.*")
t("day5_morning","day5_morning_watchers_1", text="*Me di la vuelta y miré atrás.*")
t("day5_morning","day5_morning_watchers_2", text="*Dentro de la entrada del colegio. La profesora Eunsu está sentada en un banco. Sea está de pie bajo un árbol. Riin mira desde la ventana de la enfermería.*")
t("day5_morning","day5_morning_watchers_3", text="*Todas en posiciones diferentes. Una escena de aspecto natural. Pero las tres me están mirando.*")
t("day5_morning","day5_morning_watchers_4", text="*Las tres sonríen.*")
t("day5_morning","day5_morning_welcome_5", name="Han Sea", text="\"Estemos juntas todo el día hoy. Nunca nos separemos.\"")
t("day5_morning","day5_morning_welcome_6", text="*Hay peso en la palabra 'nunca'.*")
t("day5_morning","day5_morning_welcome_7", name="Riin", text="\"Todavía falta terminar el chequeo médico.\"")
t("day5_morning","day5_morning_welcome_8", text="*Riin sonríe. Su mano está en el bolsillo de la bata. Algo abultado dentro.*")
t("day5_morning","day5_morning_welcome_9", name="Riin", text="\"Ven a la enfermería después de clase. ...Asegúrate de venir.\"")
t("day5_morning","day5_morning_welcome_10", text="*Las tres sonrisas se superponen ante mis ojos.*")
t("day5_morning","day5_morning_welcome_11", text="*La misma sonrisa. El mismo ángulo. La misma profundidad. El mismo calor.*")
t("day5_morning","day5_morning_welcome_12", text="*...La sonrisa de una cazadora.*")
t("day5_morning","day5_morning_welcome_13", text="*Y yo soy la presa. Ya dentro de la jaula.*")
t("day5_morning","day5_morning_classroom_4", text="*Palabras escritas en la pizarra. La letra de la profesora Eunsu.*")
t("day5_morning","day5_morning_classroom_5", text="*'Ceremonia de Graduación'*")
t("day5_morning","day5_morning_classroom_6", text="*...¿Ceremonia de graduación? ¿Solo cinco días desde que me transferí? ¿Qué graduación?*")
t("day5_morning","day5_morning_class_5", text="*La profesora se da la vuelta. Me mira. Solo a mí.*")
t("day5_morning","day5_morning_class_6", name="Park Eunsu", text="\"Algunas alumnas tardan tres años en darse cuenta de eso, pero nuestra clase es muy especial...\"")
t("day5_morning","day5_morning_class_7", name="Park Eunsu", text="\"...Con cinco días es suficiente.\"")
t("day5_morning","day5_morning_class_8", text="*El aula queda en silencio. No se oye ni la respiración.*")
t("day5_morning","day5_morning_class_9", name="Park Eunsu", text="\"{name}, tu graduación también... es hoy.\"")
t("day5_morning","day5_morning_class_10", text="*La profesora sonríe. Con calidez. Como si me felicitara.*")
t("day5_morning","day5_morning_class_11", text="*...Todas las demás alumnas del aula me miran. Treinta caras. Nadie se mueve.*")
t("day5_morning","day5_morning_class_12", text="*Parece que nadie respira. Como maniquíes. Como muñecas.*")
t("day5_morning","day5_morning_class_13", text="*Sea me coge la mano. Con fuerza. Me duelen los dedos.*")
t("day5_morning","day5_morning_class_14", text="*Tengo que salir de este aula. Tengo que aguantar hasta el almuerzo. Entonces me muevo.*")
t("day5_morning","day5_morning_class_15", text="*...¿Podré aguantar?*")
t("day5_morning","day5_morning_note_3", text="*'Almuerzo — pasillo del fondo, 3.ª planta, edificio antiguo. Hay una salida de emergencia. La ruta que encontró Seolhwa-senpai. Encontré la vía de escape. — Yuna'*")
t("day5_morning","day5_morning_note_4", text="*La ruta que encontró Seolhwa. La mismísima ruta que Seolhwa me contó en el sueño de anoche.*")
t("day5_morning","day5_morning_note_5", text="*¿Cómo lo supo Yuna? ...¿También se encontró Yuna con Seolhwa?*")
t("day5_morning","day5_morning_note_6", text="*Meto la nota en el bolsillo. El corazón me late. Siento algo llamado esperanza por primera vez en cuatro días.*")
t("day5_morning","day5_morning_note_7", text="*El almuerzo. Esa es la única oportunidad.*")
t("day5_morning","day5_morning_no_note", text="*Terminó la clase. Tengo que encontrar una forma de escapar por mi cuenta. Puede haber una salida de emergencia por el lado del edificio antiguo...*")

# ─────────────────────────────────────────────
# day5_lunch (81 Korean entries)
# ─────────────────────────────────────────────
t("day5_lunch","day5_lunch_start_3", text="*Hora del almuerzo.*")
t("day5_lunch","day5_lunch_start_4", text="*Sea me suelta el brazo. Solo por un momento.*")
t("day5_lunch","day5_lunch_start_5", text="*...Esta es mi oportunidad.*")
t("day5_lunch","day5_lunch_start_6", text="*Pasillo del fondo. Tercera planta. Edificio antiguo.*")
t("day5_lunch","day5_lunch_start_7", text="*Yuna estará esperando.*")
t("day5_lunch","day5_lunch_start_8", text="*Me muevo.*")
t("day5_lunch","day5_lunch_yuna_5", text="*Yuna está en el pasillo. Me hace señas.*")
t("day5_lunch","day5_lunch_yuna_6", name="Choi Yuna", text="\"Senpai, por aquí.\"")
t("day5_lunch","day5_lunch_yuna_7", text="*Yuna señala el fondo del pasillo. Una puerta.*")
t("day5_lunch","day5_lunch_yuna_8", name="Choi Yuna", text="\"Esta es la salida de emergencia. Desde aquí hay una escalera exterior.\"")
t("day5_lunch","day5_lunch_yuna_9", text="\"¿La encontró Seolhwa?\"")
t("day5_lunch","day5_lunch_yuna_10", name="Choi Yuna", text="\"Sí. En sus archivos había un mapa. La ruta de escape.\"")
t("day5_lunch","day5_lunch_yuna_11", text="*Yuna tiembla ligeramente. Pero los ojos son firmes.*")
t("day5_lunch","day5_lunch_yuna_12", name="Choi Yuna", text="\"Vamos, senpai. Antes de que nos vean.\"")
t("day5_lunch","day5_lunch_escape_3", text="*¿Qué hago?*",
  choices=["Huir con Yuna", "Huir sola", "Quedarme"])
t("day5_lunch","day5_lunch_left_2", text="*Sea me llama desde abajo. 'Hoy come conmigo.' Una orden, no una petición.*")
t("day5_lunch","day5_lunch_left_3", text="*...No puedo escabullirme. Sea está vigilando.*")
t("day5_lunch","day5_lunch_sea_talk_1", text="*Sea me espera en el aula. Con la fiambrera preparada.*")
t("day5_lunch","day5_lunch_sea_talk_1c", name="Han Sea", text="\"Hoy también traje bastante. Come.\"")
t("day5_lunch","day5_lunch_sea_cb_choco_2", text="*Sea me ofrece la leche de chocolate. La misma de siempre.*")
t("day5_lunch","day5_lunch_sea_cb_lunch_2", text="*Sea abre la fiambrera. Los mismos platos. Exactamente los mismos.*")
t("day5_lunch","day5_lunch_sea_cb_vulnerability", text="*...Sea. Que una vez dijo que quería salir.*")
t("day5_lunch","day5_lunch_sea_cb_vulnerability_2", name="Han Sea", text="\"...{name}. ¿Por qué me miras así?\"")
t("day5_lunch","day5_lunch_sea_cb_default_2", text="*Sea come en silencio. Los ojos no se apartan de mí.*")
t("day5_lunch","day5_lunch_sea_tears", text="*Sea deja los palillos.*")
t("day5_lunch","day5_lunch_sea_tears_2", name="Han Sea", text="\"...{name}. ¿Piensas irte?\"")
t("day5_lunch","day5_lunch_sea_tears_3", text="*Las manos de Sea tiemblan ligeramente. Los ojos, brillantes.*")
t("day5_lunch","day5_lunch_sea_block_mid", text="*Sea me bloquea el paso.*",
  choices=["Esquivarla", "Hablarle"])
t("day5_lunch","day5_lunch_sea_push_2", text="*Me aparto de Sea. Ella no me sigue.*")
t("day5_lunch","day5_lunch_sea_persuade", text="\"Sea. Ven conmigo.\"")
t("day5_lunch","day5_lunch_sea_persuade_2", name="Han Sea", text="\"...No puedo.\"")
t("day5_lunch","day5_lunch_sea_persuade_3", text="\"¡Sí puedes! Seolhwa también quería salir. Tú también—\"")
t("day5_lunch","day5_lunch_sea_persuade_4", name="Han Sea", text="\"¡Seolhwa fracasó! ¡Y mira lo que le pasó!\"")
t("day5_lunch","day5_lunch_sea_persuade_5", text="*Sea chilla. Las lágrimas le ruedan por las mejillas.*")
t("day5_lunch","day5_lunch_sea_persuade_6", name="Han Sea", text="\"...Lo siento. Pero yo... ya no puedo luchar. Estoy demasiado cansada.\"")
t("day5_lunch","day5_lunch_sea_persuade_7", text="\"Sea...\"")
t("day5_lunch","day5_lunch_sea_persuade_8", name="Han Sea", text="\"Ve. ...{name}. Ve y cuéntaselo al mundo.\"")
t("day5_lunch","day5_lunch_sea_persuade_9", text="*Sea se hace a un lado. Con los ojos cerrados.*")
t("day5_lunch","day5_lunch_right_2", text="*Paso junto a Sea. Ella no dice nada.*")
t("day5_lunch","day5_lunch_right_3", text="*Solo... la oigo llorar en voz baja.*")
t("day5_lunch","day5_lunch_riin_talk_1", text="*La enfermería. Riin está en su mesa.*")
t("day5_lunch","day5_lunch_riin_talk_1b", name="Kang Riin", text="\"Vaya, hoy también viniste. Siéntate.\"")
t("day5_lunch","day5_lunch_riin_cb_drink_2", name="Kang Riin", text="\"Bébetelo. Es bueno para los nervios.\"")
t("day5_lunch","day5_lunch_riin_cb_drink_3", text="*...El mismo olor de siempre. Ligeramente dulce. Ligeramente extraño.*")
t("day5_lunch","day5_lunch_riin_cb_met_2", name="Kang Riin", text="\"Sí, nos hemos visto. ¿Estás bien? Pareces diferente hoy.\"")
t("day5_lunch","day5_lunch_riin_cb_default_2", text="*Riin me mira. Con aquella sonrisa tranquila de siempre.*")
t("day5_lunch","day5_lunch_riin_confront_3", text="\"...¿Qué le hiciste a Seolhwa?\"")
t("day5_lunch","day5_lunch_riin_confront_4", name="Kang Riin", text="\"...¿Seolhwa? ¿De quién hablas?\"")
t("day5_lunch","day5_lunch_riin_confront_5", text="\"Lee Seolhwa. La alumna que estaba en mi asiento.\"")
t("day5_lunch","day5_lunch_riin_confront_6", name="Kang Riin", text="\"...No sé de qué hablas. Siéntate, {name}.\"")
t("day5_lunch","day5_lunch_riin_confront_7", text="*La voz de Riin sigue siendo apacible. Pero los ojos son diferentes.*")
t("day5_lunch","day5_lunch_continue_3", text="*Salgo de la enfermería. El pasillo está vacío.*")
t("day5_lunch","day5_lunch_continue_4", text="*Tercera planta. Edificio antiguo. Allá voy.*")
t("day5_lunch","day5_lunch_eunsu_face_2", text="*La profesora Eunsu está en el pasillo. Me sonríe.*")
t("day5_lunch","day5_lunch_eunsu_face_3", name="Park Eunsu", text="\"¿Adónde vas, {name}? Hoy quédate aquí.\"")
t("day5_lunch","day5_lunch_eunsu_cb_app_2", name="Park Eunsu", text="\"Me alegra que lo entiendas. Vamos al aula.\"")
t("day5_lunch","day5_lunch_eunsu_cb_visit_2", name="Park Eunsu", text="\"¿Sí? Pero hoy no hace falta que vayas. Yo te cuido.\"")
t("day5_lunch","day5_lunch_eunsu_cb_default_2", text="*La profesora Eunsu sigue sonriendo. Tranquilamente.*")
t("day5_lunch","day5_lunch_eunsu_plea", text="\"Profesora. Por favor, déjeme salir.\"")
t("day5_lunch","day5_lunch_eunsu_plea_2", name="Park Eunsu", text="\"...¿Salir? ¿Adónde?\"")
t("day5_lunch","day5_lunch_eunsu_plea_3", text="\"A casa. A mi verdadera casa. Tengo familia. Amigos. Mi vida de antes.\"")
t("day5_lunch","day5_lunch_eunsu_plea_4", name="Park Eunsu", text="\"...{name}. El mundo exterior es peligroso. Frío. Aquí estás a salvo.\"")
t("day5_lunch","day5_lunch_eunsu_plea_5", text="\"¡No quiero estar a salvo así! ¡Quiero salir!\"")
t("day5_lunch","day5_lunch_eunsu_final_max", name="Park Eunsu", text="\"...Lo siento, {name}. Pero ya no puedes irte.\"")
t("day5_lunch","day5_lunch_eunsu_break_2", text="*La profesora Eunsu extiende la mano.*")
t("day5_lunch","day5_lunch_eunsu_break_3", name="Park Eunsu", text="\"Vamos. Es hora de tu graduación.\"")
t("day5_lunch","day5_lunch_eunsu_break_4", text="*No. No voy a dejar que me lleve.*")
t("day5_lunch","day5_lunch_eunsu_break_5", text="*Salgo corriendo. La profesora me llama.*")
t("day5_lunch","day5_lunch_eunsu_break_6", name="Park Eunsu", text="\"...{name}. Espera.\"")
t("day5_lunch","day5_lunch_eunsu_stay_3", text="*La profesora Eunsu me lleva de vuelta al aula.*")
t("day5_lunch","day5_lunch_eunsu_stay_4", name="Park Eunsu", text="\"{name}, tomaste la decisión correcta. Aquí estarás a salvo para siempre.\"")

# ─────────────────────────────────────────────
# day5_afterschool
# ─────────────────────────────────────────────
t("day5_afterschool","day5_after_escaped_5", text="*Está lloviendo. Las gotas me golpean la cara. Frío. Pero este frío... es prueba de que estoy viva.*")
t("day5_afterschool","day5_after_escaped_6", text="*Por primera vez... desde que llegué a este colegio, por primera vez, respiro el aire del exterior.*")
t("day5_afterschool","day5_after_escaped_7", text="*Inhalé. Profundo. Tan profundo que sentí que los pulmones me iban a estallar. ...El olor es diferente. No a desinfectante. No a flores de cerezo. Solo olor a lluvia. Olor a tierra. El olor del mundo.*")
t("day5_afterschool","day5_after_escaped_8", text="*Corrí. A cualquier parte. Lo más lejos posible de este colegio. Las piernas me tiemblan. Las rodillas ceden. Sigo corriendo.*")
t("day5_afterschool","day5_after_escaped_yuna_2", text="*Corrimos hasta detenernos. Después de alejarnos lo suficiente del colegio. Bajo un farol.*")
t("day5_afterschool","day5_after_escaped_yuna_3", name="Choi Yuna", text="\"Senpai...\"")
t("day5_afterschool","day5_after_escaped_yuna_4", name="Choi Yuna", text="\"Salimos...\"")
t("day5_afterschool","day5_after_escaped_yuna_5", text="\"Salimos. Salimos, Yuna.\"")
t("day5_afterschool","day5_after_escaped_solo_2", text="*No puedo parar. Aún no he llegado suficientemente lejos. Más. Más lejos.*")
t("day5_afterschool","day5_after_captured_6", name="Park Eunsu", text="\"...¿Intentaste huir? ¿Sabes lo preocupada que estaba?\"")
t("day5_afterschool","day5_after_captured_7", name="Kang Riin", text="\"Prepararé el chequeo final.\"")
t("day5_afterschool","day5_after_captured_8", name="Kang Riin", text="\"Solo una extracción de sangre y un suero y listo. Esta es la última vez.\"")
t("day5_afterschool","day5_after_captured_9", text="*'Última vez.' Esa palabra pesa. Cuando esto termine... ¿qué pasará? ¿Como Seolhwa?*")
t("day5_afterschool","day5_after_captured_10", text="*La enfermera Riin desinfecta el interior de mi codo. El frío del algodón con alcohol toca mi piel. ...No puedo rendirme aquí. Todavía no ha terminado.*")
t("day5_afterschool","day5_after_captured_choice", text="*...¿Qué hago?*",
  choices=["Resistir", "Aceptarlo"])
t("day5_afterschool","day5_after_captured_resist_4", text="*En ese momento. Se fue la luz.*")
t("day5_afterschool","day5_after_captured_resist_5", name="Park Eunsu", text="\"...¿Qué?\"")
t("day5_afterschool","day5_after_captured_resist_6", name="Kang Riin", text="\"¿Un apagón? ¿A estas horas?\"")
t("day5_afterschool","day5_after_captured_resist_7", text="*En la oscuridad... siento una mano. Una mano fría y translúcida. Está soltando las correas de cuero.*")
t("day5_afterschool","day5_after_captured_resist_8", text="*...Seolhwa. Las correas se soltaron. Seolhwa me coge la mano. Pensé que una mano translúcida no podría agarrar nada... pero me sujeta.*")
t("day5_afterschool","day5_after_captured_resist_9", text="*Me arrastra por la oscuridad. Ahogando mis pasos. Hacia la salida de emergencia.*")
t("day5_afterschool","day5_after_captured_submit_3", text="*...Se calienta. Siento que el cuerpo se derrite. Los pensamientos se difuminan.*")
t("day5_afterschool","day5_after_captured_submit_4", text="*Hay algo... que estoy olvidando. ¿Qué estoy olvidando? Era importante... ¿qué era...?*")
t("day5_afterschool","day5_after_stayed_5", name="Park Eunsu", text="\"La profesora te protegerá de todo. No tienes que preocuparte por nada.\"")
t("day5_afterschool","day5_after_stayed_6", text="*Me senté. Sea se sienta a mi lado. Riin nos sirve una taza de té.*")
t("day5_afterschool","day5_after_stayed_7", name="Park Eunsu", text="\"...{name} solo tiene que estar al lado de su profesora. Para siempre.\"")
t("day5_afterschool","day5_after_stayed_8", text="*La profesora Eunsu sonríe. Una sonrisa cálida.*")
t("day5_afterschool","day5_after_stayed_9", text="*...¿Esta sonrisa siempre fue tan aterradora? No. No da miedo. ...No da miedo. ...¿Por qué no da miedo?*")
t("day5_afterschool","day5_after_stayed_10", text="*Bebí el té. Está caliente. Se siente bien. ...Hay algo que siento que estoy olvidando. Qué era. ...Da igual. Puedo olvidarlo. Aquí estoy a salvo.*")

# ─────────────────────────────────────────────
# day5_night (84 Korean entries)
# ─────────────────────────────────────────────
t("day5_night","day5_ending_true_9", text="*La luz del amanecer entra por la ventana.*")
t("day5_night","day5_ending_true_10", text="*Un ordenador de la comisaría. Tecleo el informe.*")
t("day5_night","day5_ending_true_11", text="*Lee Seolhwa. Fecha de nacimiento. Fecha de ingreso al colegio. Fecha de desaparición.*")
t("day5_night","day5_ending_true_12", text="*Lo escribo todo. Sin omitir nada.*")
t("day5_night","day5_ending_true_13", text="*El detective me escucha en silencio. Anota sin parar.*")
t("day5_night","day5_ending_true_14", text="*A mediodía, los furgones de la policía rodean el colegio.*")
t("day5_night","day5_ending_true_15", text="*El colegio queda en silencio. La profesora Eunsu es detenida. Riin es detenida.*")
t("day5_night","day5_ending_true_16", text="*Los alumnos salen del edificio. Con expresiones aturdidas. Sin saber dónde están.*")
t("day5_night","day5_ending_true_17", text="*...Sea.*")
t("day5_night","day5_ending_true_18", name="Han Sea", text="\"...{name}.\"")
t("day5_night","day5_ending_true_19", text="*Sea me mira. Con ojos confusos. Como si no recordara nada.*")
t("day5_night","day5_ending_true_20", text="\"Sea. Estás fuera. Ya estás fuera.\"")
t("day5_night","day5_ending_true_21", name="Han Sea", text="\"...¿Fuera? ¿De dónde?\"")
t("day5_night","day5_ending_true_22", text="*Sea parpadea. Los recuerdos van regresando poco a poco.*")
t("day5_night","day5_ending_true_23", name="Han Sea", text="\"...Ah.\"")
t("day5_night","day5_ending_true_24", text="*Un sonido breve. Y luego, las lágrimas.*")
t("day5_night","day5_ending_true_25", text="*Sea llora. Yo también lloro.*")
t("day5_night","day5_ending_true_subtitle", text="Graduación — Por fin, desde un aula que nunca pudo graduarse.")
t("day5_night","day5_postcredit_6", text="*Un año después.*")
t("day5_night","day5_postcredit_7", text="*Coloco flores ante una lápida.*")
t("day5_night","day5_postcredit_8", text="*Lee Seolhwa. El nombre grabado en la piedra.*")
t("day5_night","day5_ending_escape_5", text="*Me escapé. Con Yuna.*")
t("day5_night","day5_ending_escape_6", text="*Publicamos las evidencias. El mundo lo supo.*")
t("day5_night","day5_ending_escape_7", text="*El colegio fue clausurado. La profesora Eunsu detenida.*")
t("day5_night","day5_ending_escape_8", text="*...Pero a los alumnos que quedaron dentro.*")
t("day5_night","day5_ending_escape_9", text="*¿Se recuperaron? ¿Volvieron sus recuerdos?*")
t("day5_night","day5_ending_escape_10", text="*No lo sé. Quizás nunca lo sepa.*")
t("day5_night","day5_ending_escape_11", text="*Pero nosotras salimos. Estamos vivas.*")
t("day5_night","day5_ending_escape_ghost", name="Lee Seolhwa", text="\"...Estaré esperándolas, senpai.\"")
t("day5_night","day5_ending_escape_subtitle", text="Superviviente — El peso de quien sobrevivió.")
t("day5_night","day5_ending_resist_5", text="*Me escapé. Sola.*")
t("day5_night","day5_ending_resist_6", text="*Las evidencias en el teléfono. La tarjeta de memoria de Seolhwa.*")
t("day5_night","day5_ending_resist_7", text="*Fui a la policía. Expliqué todo.*")
t("day5_night","day5_ending_resist_8", text="*Pero el colegio... ya estaba vacío.*")
t("day5_night","day5_ending_resist_9", text="*Ni la profesora Eunsu, ni Riin. Nadie.*")
t("day5_night","day5_ending_resist_10", text="*Solo los pupitres vacíos. Y el aula.*")
t("day5_night","day5_ending_resist_11", text="*...¿A dónde fueron Sea y los demás?*")
t("day5_night","day5_ending_resist_12", text="*No lo sé. Todavía.*")
t("day5_night","day5_ending_resist_subtitle", text="Escape incompleto — Aún no ha terminado.")
t("day5_night","day5_ending_cage_5", text="*...{name}.*")
t("day5_night","day5_ending_cage_6", name="Park Eunsu", text="\"Buenos días, {name}.\"")
t("day5_night","day5_ending_cage_7", text="*El aula. La mañana. La profesora Eunsu en el estrado.*")
t("day5_night","day5_ending_cage_8", text="*...¿Cuántos días han pasado?*")
t("day5_night","day5_ending_cage_9", text="*No lo sé. Ya no lo sé.*")
t("day5_night","day5_ending_cage_10", text="*Sea está a mi lado. Sonriendo.*")
t("day5_night","day5_ending_cage_11", name="Han Sea", text="\"{name}, ¿estás bien?\"")
t("day5_night","day5_ending_cage_12", text="\"Sí... estoy bien.\"")
t("day5_night","day5_ending_cage_13", text="*Habré olvidado algo. Algo importante.*")
t("day5_night","day5_ending_cage_14", text="*Pero no sé qué.*")
t("day5_night","day5_ending_cage_15", text="*...No importa. Aquí estoy a salvo.*")
t("day5_night","day5_ending_cage_16", text="*La clase empieza. La voz de la profesora resuena en el aula.*")
t("day5_night","day5_ending_cage_subtitle", text="La jaula — Vida escolar eterna.")
t("day5_night","day5_ending_forget_6", text="*...Dónde estoy.*")
t("day5_night","day5_ending_forget_7", text="*El techo blanco. El olor a desinfectante.*")
t("day5_night","day5_ending_forget_8", text="*...La enfermería.*")
t("day5_night","day5_ending_forget_9", name="Kang Riin", text="\"{name}. ¿Estás despierta?\"")
t("day5_night","day5_ending_forget_10", text="*Riin sonríe. Una sonrisa tranquila.*")
t("day5_night","day5_ending_forget_11", name="Kang Riin", text="\"Todo ha terminado. Ya puedes descansar.\"")
t("day5_night","day5_ending_forget_12", text="\"...¿Qué terminó?\"")
t("day5_night","day5_ending_forget_13", name="Kang Riin", text="\"Todo. El tratamiento. Los recuerdos. Todo.\"")
t("day5_night","day5_ending_forget_14", text="*...Recuerdos. ¿Qué estaba recordando?*")
t("day5_night","day5_ending_forget_15", text="*No sé. Ya no sé.*")
t("day5_night","day5_ending_forget_16", text="*...¿Importa? Aquí estoy bien. Cálida. A salvo.*")
t("day5_night","day5_ending_forget_ghost", name="Lee Seolhwa", text="Huye")
t("day5_night","day5_ending_forget_subtitle", text="Reinicio — Todo vuelve al principio.")
t("day5_night","day5_ending_ghost_6", text="*El exterior del colegio. La lluvia sigue cayendo.*")
t("day5_night","day5_ending_ghost_7", text="*Estoy de pie frente a la puerta.*")
t("day5_night","day5_ending_ghost_8", text="*...No recuerdo cómo salí.*")
t("day5_night","day5_ending_ghost_9", text="*Alguien me sacó. Una mano fría.*")
t("day5_night","day5_ending_ghost_10", name="Lee Seolhwa", text="\"...Sal.\"")
t("day5_night","day5_ending_ghost_11", text="*Me doy la vuelta. Seolhwa está de pie detrás de mí.*")
t("day5_night","day5_ending_ghost_12", name="Lee Seolhwa", text="\"Corre. No mires atrás.\"")
t("day5_night","day5_ending_ghost_13", text="\"¿Seolhwa? ¿Cómo...?\"")
t("day5_night","day5_ending_ghost_14", name="Lee Seolhwa", text="\"No hay tiempo. Ve.\"")
t("day5_night","day5_ending_ghost_15", text="*Seolhwa empuja suavemente.*")
t("day5_night","day5_ending_ghost_16", text="*Sus manos son frías. Translúcidas. Apenas perceptibles.*")
t("day5_night","day5_ending_ghost_17", name="Lee Seolhwa", text="\"...Vive bien. Por mí también.\"")
t("day5_night","day5_ending_ghost_18", text="*Me di la vuelta. Eché a correr.*")
t("day5_night","day5_ending_ghost_whisper", name="Lee Seolhwa", text="\"Sal de aquí\"")
t("day5_night","day5_ending_ghost_subtitle", text="El eco — El registro de quien no pudo graduarse.")

# ─────────────────────────────────────────────────────────────
# Apply all translations
# ─────────────────────────────────────────────────────────────

def process(stem):
    en_path = os.path.join(EN_DIR, stem + ".json")
    es_path = os.path.join(ES_DIR, stem + ".json")
    en = load(en_path)
    es = load(es_path)
    overrides = T.get(stem, {})
    changed = 0
    for key, entry in es.items():
        ov = overrides.get(key, {})
        en_entry = en.get(key, {})
        # name
        if 'name' in ov:
            if es[key].get('name') != ov['name']:
                es[key]['name'] = ov['name']
                changed += 1
        elif has_kor(es[key].get('name','')):
            en_name = en_entry.get('name','')
            es[key]['name'] = NAME_MAP.get(en_name, en_name)
            changed += 1
        # text
        if 'text' in ov:
            if es[key].get('text') != ov['text']:
                es[key]['text'] = ov['text']
                changed += 1
        elif has_kor(es[key].get('text','')):
            # Use EN text as fallback with "Me"->"Yo" in narration
            en_text = en_entry.get('text','')
            es[key]['text'] = en_text
            changed += 1
        # choices
        if 'choices' in ov:
            if es[key].get('choices') != ov['choices']:
                es[key]['choices'] = ov['choices']
                changed += 1
        elif 'choices' in es[key]:
            choices = es[key]['choices']
            if isinstance(choices, list) and any(has_kor(c) for c in choices):
                en_choices = en_entry.get('choices', [])
                if en_choices:
                    es[key]['choices'] = en_choices
                    changed += 1
    save(es_path, es)
    sys.stdout.write(f"  {stem}: {changed} entries updated\n")
    sys.stdout.flush()
    return changed

stems = [
    "day1_morning","day1_lunch","day1_afterschool","day1_night",
    "day2_morning","day2_lunch","day2_afterschool","day2_night",
    "day3_morning","day3_lunch","day3_afterschool","day3_night",
    "day4_morning","day4_lunch","day4_afterschool","day4_night",
    "day5_morning","day5_lunch","day5_afterschool","day5_night",
]

total = 0
for s in stems:
    total += process(s)
sys.stdout.write(f"\nTotal: {total} entries updated\n")
